version: '3.8'

services:
  redis-server:
    image: redis:alpine   
    ports:
      - "6379:6379"
    restart: always 

  api-gateway:
    image: wh493757101-oss/visionguard:latest
    ports:
      - "8000:8000"
    depends_on:
      - redis-server    
    restart: always
    environment:
      - REDIS_HOST=redis-server 

  vision-worker:
    image: wh493757101-oss/visionguard:latest
    command: python worker.py 
    depends_on:
      - redis-server        
    restart: always
    environment:
      - REDIS_HOST=redis-server
    deploy:
      replicas: 3